- name: Identify and print specific interface
  hosts: localhost

  vars:
    target_mac: "48:2a:e3:2c:18:81"

  tasks:
# Use set_fact module to load a fact to the target inventory
    - name: Find the_interface for target_mac
      set_fact:
        the_interface: "{{ item }}"
      when:
        - ansible_facts[item]['macaddress'] is defined
        - ansible_facts[item]['macaddress'] == target_mac
      loop: "{{ ansible_facts['interfaces'] }}"

    - name: Display the_interface
      debug:
        var: the_interface
