- name: Install and configure cups
  hosts: all
  vars:
    pkg_name:
      - cups
      - avahi
    srv_name:
      - cups
      - avahi-daemon
    dev_url: "ipp://serverc.lab.example.com:631/printers/rht-printer"

  tasks:
  - name: Ensur packages are installed
    yum:
      name: "{{ pkg_name }}"
      state: present

  - name: Ensure services are running
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop: "{{ srv_name }}"

  - name: Ensure port is open in firewalld
    firewalld:
      service: mdns
      immediate: true
      permanent: true
      state: enabled

  - name: check if print queue exists
    command: "lpstat -p myprinter"
    ignore_errors: true
    register: output

  - name: Create print queue
    command: "lpadmin -p myprinter -v {{ dev_url }} -m everywhere -E"
    when: output.rc != 0

  - name: make print queue default
    command: lpadmin -d my-printer
